site_name: MOF
site_url: https://docs.rkdev.info
repo_name: pointgoal/mof-docs
repo_url: https://github.com/pointgoal/mof-docs

theme:
  favicon: img/favicon.ico
  name: material
  language: en
  features:
    - navigation.top
 #   - navigation.expand

plugins:
  - swagger-ui-tag
  - glightbox
  - mkdocs-video
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        zh:
          name: 简体中文
          build: true
      nav_translations:
        zh:
          Overview: 介绍
          Community: 社区
          Channel: 沟通渠道
          Contribution: 贡献
          Code of conduct: 开发者公约
          Concept: 概念
          Core features: 核心功能
          Auth Management: 权限管理
          Offer Management: 价格管理
          Provider Management: 云厂商管理
          Jarvis: Jarvis 引擎
          Install: 安装
          Reference: 参考
          Provider: 云厂商
          Alibaba Cloud: 阿里云
          Tencent Cloud: 腾讯云
          Guides: 用户指南
          Tutorial: 教程
          Operator: 运维
          Developer: 开发

markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


nav:
  - 'Overview': 'index.md'
  - 'Concept':
      - 'Core features': 'concept/overview.md'
      - 'Auth Management': 'concept/auth.md'
      - 'Offer Management': 'concept/offer.md'
      - 'Provider Management': 'concept/provider.md'
      - 'Jarvis': 'concept/jarvis.md'
  - 'Install': 'install/index.md'
  - 'Guides':
      - 'Tutorial':
          - 'Overview': 'guide/tutorial/index.md'
          - 'Add provider': 'guide/tutorial/add-provider.md'
          - 'Cost analysis': 'guide/tutorial/cost-analysis.md'
          - 'Cost forecast': 'guide/tutorial/cost-forecast.md'
          - 'Cost optimization': 'guide/tutorial/cost-opt.md'
          - 'Reserved instances': 'guide/tutorial/cost-ri.md'
          - 'Tagging': 'guide/tutorial/tag.md'
      - 'Operator':
          - 'Overview': 'guide/operator/index.md'
      - 'Developer':
          - 'Overview': 'guide/developer/index.md'
  - 'Reference':
      - 'Provider':
          - 'AWS': 'reference/provider/aws.md'
          - 'Alibaba Cloud': 'reference/provider/alibaba-cloud.md'
          - 'Tencent Cloud': 'reference/provider/tencent-cloud.md'
      - 'Jarvis':
          - 'V1': 'reference/jarvis/v1.md'
      - 'API': 'reference/api.md'
      - 'Web UI': 'reference/web-ui.md'
  - 'Community':
      - 'Channel': 'community/channel.md'
      - 'Contribution': 'community/contribution.md'
      - 'Code of conduct': 'community/code-of-conduct.md'

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/pointgoal/repositories
    - icon: fontawesome/brands/github
      link: https://github.com/pointgoal

copyright: Copyright &copy; 2022 pointgoal